// Preview only. Run: swift scripts/preview-private-network-icon.swift <output.png>
// Production assets remain generated by generate-icons.swift.
import AppKit
let blue = NSColor(srgbRed: 0, green: 0.4, blue: 1, alpha: 1)
let pale = NSColor(srgbRed: 224.0/255, green: 237.0/255, blue: 1, alpha: 1)
// Project-owned storage cylinder; no third-party logo artwork is used.
func storageLogo(_ color: NSColor) -> NSImage {
    let image = NSImage(size: NSSize(width: 256, height: 256))
    image.lockFocus()
    color.setStroke()
    let body = NSBezierPath()
    body.move(to: NSPoint(x: 42, y: 190))
    body.line(to: NSPoint(x: 42, y: 66))
    body.curve(to: NSPoint(x: 214, y: 66), controlPoint1: NSPoint(x: 42, y: 20), controlPoint2: NSPoint(x: 214, y: 20))
    body.line(to: NSPoint(x: 214, y: 190))
    body.lineWidth = 18
    body.lineCapStyle = .round
    body.stroke()
    let top = NSBezierPath(ovalIn: NSRect(x: 42, y: 158, width: 172, height: 64))
    top.lineWidth = 18
    top.stroke()
    let middle = NSBezierPath()
    middle.move(to: NSPoint(x: 42, y: 126))
    middle.curve(to: NSPoint(x: 214, y: 126), controlPoint1: NSPoint(x: 42, y: 80), controlPoint2: NSPoint(x: 214, y: 80))
    middle.lineWidth = 14
    middle.stroke()
    image.unlockFocus()
    return image
}
let blueLogo = storageLogo(blue)
let blackLogo = storageLogo(.black)

func polygon(_ points: [(CGFloat, CGFloat)]) {
    let p = NSBezierPath(); p.move(to: NSPoint(x: points[0].0, y: points[0].1))
    for (x,y) in points.dropFirst() { p.line(to: NSPoint(x: x, y: y)) }
    p.close(); p.fill()
}
// Network boundaries and a continuous route replace generic letter/link symbols.
func stroke(_ points: [(CGFloat, CGFloat)], width: CGFloat, rounded: Bool = true) {
    let p = NSBezierPath(); p.move(to: NSPoint(x: points[0].0, y: points[0].1))
    for (x,y) in points.dropFirst() { p.line(to: NSPoint(x: x, y: y)) }
    p.lineWidth = width; p.lineCapStyle = rounded ? .round : .butt
    p.lineJoinStyle = .round; p.stroke()
}
// Optical balance: center the LAN vertically and keep the external route compact.
func mark(_ concept: Int, background: NSColor) {
    let boundary = NSBezierPath()
    boundary.move(to: NSPoint(x: 28, y: 62))
    boundary.line(to: NSPoint(x: 28, y: 69))
    boundary.curve(to: NSPoint(x: 36, y: 77), controlPoint1: NSPoint(x: 28, y: 74), controlPoint2: NSPoint(x: 31, y: 77))
    boundary.line(to: NSPoint(x: 74, y: 77))
    boundary.curve(to: NSPoint(x: 82, y: 69), controlPoint1: NSPoint(x: 79, y: 77), controlPoint2: NSPoint(x: 82, y: 74))
    boundary.line(to: NSPoint(x: 82, y: 31))
    boundary.curve(to: NSPoint(x: 74, y: 23), controlPoint1: NSPoint(x: 82, y: 26), controlPoint2: NSPoint(x: 79, y: 23))
    boundary.line(to: NSPoint(x: 36, y: 23))
    boundary.curve(to: NSPoint(x: 28, y: 31), controlPoint1: NSPoint(x: 31, y: 23), controlPoint2: NSPoint(x: 28, y: 26))
    boundary.line(to: NSPoint(x: 28, y: 38))
    boundary.lineWidth = 5; boundary.lineCapStyle = .round; boundary.stroke()
    // Short orthogonal route enters the middle of the left-side opening.
    let route = NSBezierPath()
    route.move(to: NSPoint(x: 10, y: 35))
    route.line(to: NSPoint(x: 13, y: 35))
    route.curve(to: NSPoint(x: 18, y: 40), controlPoint1: NSPoint(x: 16, y: 35), controlPoint2: NSPoint(x: 18, y: 37))
    route.line(to: NSPoint(x: 18, y: 45))
    route.curve(to: NSPoint(x: 23, y: 50), controlPoint1: NSPoint(x: 18, y: 48), controlPoint2: NSPoint(x: 20, y: 50))
    route.line(to: NSPoint(x: 37, y: 50))
    route.lineWidth = 5; route.lineCapStyle = .round; route.stroke()
    NSBezierPath(roundedRect: NSRect(x: 5, y: 30, width: 10, height: 10), xRadius: 3, yRadius: 3).fill()
    let logo = background == pale ? blueLogo : blackLogo
    logo.draw(in: NSRect(x: 39, y: 33, width: 34, height: 34),
        from: NSRect(x: 24, y: 20, width: 208, height: 220), operation: .sourceOver, fraction: 1)
}
func placedMark(_ concept: Int, x: CGFloat, y: CGFloat, size: CGFloat, color: NSColor) {
    NSGraphicsContext.saveGraphicsState()
    let t = NSAffineTransform(); t.translateX(by: x, yBy: y); t.scale(by: size/100); t.concat()
    color.setFill(); color.setStroke()
    mark(concept, background: color == blue ? pale : NSColor(srgbRed: 0.94, green: 0.95, blue: 0.97, alpha: 1))
    NSGraphicsContext.restoreGraphicsState()
}
func text(_ string: String, x: CGFloat, y: CGFloat, size: CGFloat, color: NSColor = .labelColor, bold: Bool = false) {
    (string as NSString).draw(at: NSPoint(x: x, y: y), withAttributes: [
        .font: NSFont.systemFont(ofSize: size, weight: bold ? .semibold : .regular), .foregroundColor: color])
}
let rep = NSBitmapImageRep(bitmapDataPlanes: nil, pixelsWide: 1100, pixelsHigh: 650,
    bitsPerSample: 8, samplesPerPixel: 4, hasAlpha: true, isPlanar: false,
    colorSpaceName: .deviceRGB, bytesPerRow: 0, bitsPerPixel: 0)!
NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: rep)
NSColor(srgbRed: 0.96, green: 0.97, blue: 0.99, alpha: 1).setFill()
NSBezierPath(rect: NSRect(x: 0, y: 0, width: 1100, height: 650)).fill()
text("C · 重心优化", x: 48, y: 580, size: 30, bold: true)
text("边框下移、连线缩短，让主体围绕图标中心展开。", x: 48, y: 541, size: 19, color: .darkGray)
NSColor.white.setFill()
NSBezierPath(roundedRect: NSRect(x: 40, y: 40, width: 1020, height: 474), xRadius: 24, yRadius: 24).fill()
pale.setFill()
NSBezierPath(roundedRect: NSRect(x: 80, y: 140, width: 300, height: 300), xRadius: 68, yRadius: 68).fill()
placedMark(0, x: 92, y: 152, size: 276, color: blue)
text("应用图标", x: 188, y: 100, size: 18, color: .darkGray)
text("收紧构图，重心回到中心", x: 460, y: 447, size: 21, bold: true)
text("内网边界与存储圆柱", x: 460, y: 408, size: 19, color: .darkGray)
text("外部端点抬高，缩短折线，保持边框间距", x: 460, y: 374, size: 19, color: .darkGray)
text("状态栏 · 放大 2 倍", x: 460, y: 309, size: 18, bold: true)
let menuBackground = NSColor(srgbRed: 0.94, green: 0.95, blue: 0.97, alpha: 1)
menuBackground.setFill()
NSBezierPath(roundedRect: NSRect(x: 452, y: 210, width: 540, height: 78), xRadius: 14, yRadius: 14).fill()
let labels = ["已连接", "连接中", "已断开", "异常"]
for state in 0..<4 {
    let sx = CGFloat(486 + state*128)
    let variant = ["connected", "working", "offline", "attention"][state]
    let resource = sourceURL.deletingLastPathComponent().appendingPathComponent("Status-\(variant)@2x.png")
    NSImage(contentsOf: resource)!.draw(in: NSRect(x: sx, y: 227, width: 44, height: 36))
    text(labels[state], x: sx-2, y: 179, size: 16, color: .darkGray)
}
text("22 × 18 pt", x: 460, y: 120, size: 15, color: .gray)
NSImage(contentsOf: sourceURL.deletingLastPathComponent().appendingPathComponent("Status-connected@2x.png"))!.draw(in: NSRect(x: 556, y: 119, width: 22, height: 18))
text("保留 fnOS 配色，所有状态共用同一主体", x: 460, y: 77, size: 17, color: .darkGray)
try rep.representation(using: .png, properties: [:])!.write(to: URL(fileURLWithPath: CommandLine.arguments[1]))
