// Preview only. Run: swift scripts/preview-icon-concepts.swift <output.png>
// Production assets remain generated by generate-icons.swift.
import AppKit
let blue = NSColor(srgbRed: 0, green: 0.4, blue: 1, alpha: 1)
let pale = NSColor(srgbRed: 224.0/255, green: 237.0/255, blue: 1, alpha: 1)
func polygon(_ points: [(CGFloat, CGFloat)]) {
    let p = NSBezierPath(); p.move(to: NSPoint(x: points[0].0, y: points[0].1))
    for (x,y) in points.dropFirst() { p.line(to: NSPoint(x: x, y: y)) }
    p.close(); p.fill()
}
// Network boundaries and a continuous route replace generic letter/link symbols.
func stroke(_ points: [(CGFloat, CGFloat)], width: CGFloat, rounded: Bool = true) {
    let p = NSBezierPath(); p.move(to: NSPoint(x: points[0].0, y: points[0].1))
    for (x,y) in points.dropFirst() { p.line(to: NSPoint(x: x, y: y)) }
    p.lineWidth = width; p.lineCapStyle = rounded ? .round : .butt
    p.lineJoinStyle = .round; p.stroke()
}
func mark(_ concept: Int, background: NSColor) {
    switch concept {
    case 0: // Opposing private-network gateways, joined by a continuous tunnel.
        let left = NSBezierPath()
        left.move(to: NSPoint(x: 38, y: 79)); left.line(to: NSPoint(x: 28, y: 79))
        left.curve(to: NSPoint(x: 17, y: 68), controlPoint1: NSPoint(x: 20, y: 79), controlPoint2: NSPoint(x: 17, y: 76))
        left.line(to: NSPoint(x: 17, y: 32))
        left.curve(to: NSPoint(x: 28, y: 21), controlPoint1: NSPoint(x: 17, y: 24), controlPoint2: NSPoint(x: 20, y: 21))
        left.line(to: NSPoint(x: 38, y: 21)); left.lineWidth = 10; left.lineCapStyle = .round; left.stroke()
        let right = left.copy() as! NSBezierPath
        let mirror = AffineTransform(m11: -1, m12: 0, m21: 0, m22: 1, tX: 100, tY: 0)
        right.transform(using: mirror); right.stroke()
        stroke([(32,50),(68,50)], width: 9)
        for x in [CGFloat(32),CGFloat(68)] {
            NSBezierPath(roundedRect: NSRect(x: x-7, y: 43, width: 14, height: 14), xRadius: 4, yRadius: 4).fill()
        }
    case 1: // Private perimeter, with an intentional passage through its center.
        let shield = NSBezierPath()
        shield.move(to: NSPoint(x: 50, y: 85)); shield.line(to: NSPoint(x: 80, y: 73))
        shield.line(to: NSPoint(x: 80, y: 46))
        shield.curve(to: NSPoint(x: 50, y: 15), controlPoint1: NSPoint(x: 80, y: 31), controlPoint2: NSPoint(x: 63, y: 21))
        shield.curve(to: NSPoint(x: 20, y: 46), controlPoint1: NSPoint(x: 37, y: 21), controlPoint2: NSPoint(x: 20, y: 31))
        shield.line(to: NSPoint(x: 20, y: 73)); shield.close(); shield.fill()
        // A negative-space tunnel passes across both sides of the private boundary.
        NSGraphicsContext.saveGraphicsState()
        background.setStroke()
        stroke([(9,50),(91,50)], width: 17)
        NSGraphicsContext.restoreGraphicsState()
        stroke([(12,50),(88,50)], width: 6)
        stroke([(76,61),(88,50),(76,39)], width: 6)
        NSBezierPath(ovalIn: NSRect(x: 7, y: 45, width: 10, height: 10)).fill()
    default: // A routed bridge through a partition between two private domains.
        stroke([(50,80),(50,64)], width: 9)
        stroke([(50,36),(50,20)], width: 9)
        let route = NSBezierPath(); route.move(to: NSPoint(x: 23, y: 32))
        route.line(to: NSPoint(x: 35, y: 32))
        route.curve(to: NSPoint(x: 65, y: 68), controlPoint1: NSPoint(x: 52, y: 32), controlPoint2: NSPoint(x: 48, y: 68))
        route.line(to: NSPoint(x: 77, y: 68)); route.lineWidth = 9; route.lineCapStyle = .round; route.stroke()
        for (x,y) in [(CGFloat(23),CGFloat(32)),(CGFloat(77),CGFloat(68))] {
            NSBezierPath(roundedRect: NSRect(x: x-11,y: y-11,width: 22,height: 22),xRadius: 6,yRadius: 6).fill()
        }
    }
}
func placedMark(_ concept: Int, x: CGFloat, y: CGFloat, size: CGFloat, color: NSColor) {
    NSGraphicsContext.saveGraphicsState()
    let t = NSAffineTransform(); t.translateX(by: x, yBy: y); t.scale(by: size/100); t.concat()
    color.setFill(); color.setStroke()
    mark(concept, background: color == blue ? pale : NSColor(srgbRed: 0.94, green: 0.95, blue: 0.97, alpha: 1))
    NSGraphicsContext.restoreGraphicsState()
}
func text(_ string: String, x: CGFloat, y: CGFloat, size: CGFloat, color: NSColor = .labelColor, bold: Bool = false) {
    (string as NSString).draw(at: NSPoint(x: x, y: y), withAttributes: [
        .font: NSFont.systemFont(ofSize: size, weight: bold ? .semibold : .regular), .foregroundColor: color])
}
let rep = NSBitmapImageRep(bitmapDataPlanes: nil, pixelsWide: 1200, pixelsHigh: 640,
    bitsPerSample: 8, samplesPerPixel: 4, hasAlpha: true, isPlanar: false,
    colorSpaceName: .deviceRGB, bytesPerRow: 0, bitsPerPixel: 0)!
NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: rep)
NSColor(srgbRed: 0.96, green: 0.97, blue: 0.99, alpha: 1).setFill()
NSBezierPath(rect: NSRect(x: 0, y: 0, width: 1200, height: 640)).fill()
text("FnCPN / Identity studies", x: 40, y: 585, size: 28, bold: true)
text("Private networks, a boundary, and a route that connects them.", x: 40, y: 552, size: 17, color: .darkGray)
let names = ["A / Linked private networks", "B / Tunnel through perimeter", "C / Route across boundary"]
for c in 0..<3 {
    let x = CGFloat(40 + c*390)
    NSColor.white.setFill()
    NSBezierPath(roundedRect: NSRect(x: x, y: 44, width: 360, height: 480), xRadius: 20, yRadius: 20).fill()
    text(names[c], x: x+24, y: 479, size: 19, bold: true)
    pale.setFill()
    NSBezierPath(roundedRect: NSRect(x: x+70, y: 224, width: 220, height: 220), xRadius: 50, yRadius: 50).fill()
    placedMark(c, x: x+76, y: 230, size: 208, color: blue)
    // Enlarged menu-bar samples: connected / working / offline / attention.
    NSColor(srgbRed: 0.94, green: 0.95, blue: 0.97, alpha: 1).setFill()
    NSBezierPath(roundedRect: NSRect(x: x+24, y: 121, width: 312, height: 66), xRadius: 12, yRadius: 12).fill()
    for state in 0..<4 {
        let sx = x + 47 + CGFloat(state)*72
        placedMark(c, x: sx, y: 134, size: 38, color: .black)
        NSColor(srgbRed: 0.94, green: 0.95, blue: 0.97, alpha: 1).setFill()
        NSBezierPath(ovalIn: NSRect(x: sx+26, y: 130, width: 16, height: 16)).fill()
        NSColor.black.setFill(); NSColor.black.setStroke()
        switch state {
        case 0: NSBezierPath(ovalIn: NSRect(x: sx+31, y: 135, width: 6, height: 6)).fill()
        case 1:
            for dot in 0..<3 { NSBezierPath(ovalIn: NSRect(x: sx+28+CGFloat(dot)*5, y: 137, width: 2.4, height: 2.4)).fill() }
        case 2:
            let p = NSBezierPath(); p.move(to: NSPoint(x: sx+30, y: 134)); p.line(to: NSPoint(x: sx+38, y: 142))
            p.move(to: NSPoint(x: sx+30, y: 142)); p.line(to: NSPoint(x: sx+38, y: 134))
            p.lineWidth = 2.5; p.lineCapStyle = .round; p.stroke()
        default:
            NSBezierPath(roundedRect: NSRect(x: sx+33, y: 137, width: 2.5, height: 7), xRadius: 1, yRadius: 1).fill()
            NSBezierPath(ovalIn: NSRect(x: sx+33, y: 132, width: 2.5, height: 2.5)).fill()
        }
    }
    text("Connected   Working   Offline   Attention", x: x+28, y: 91, size: 14, color: .darkGray)
    text("Menu-bar symbols shown at 2x", x: x+73, y: 64, size: 13, color: .gray)
}
let data = rep.representation(using: .png, properties: [:])!
try data.write(to: URL(fileURLWithPath: CommandLine.arguments[1]))
