#!/usr/bin/env python3
"""Generate native catalogs and the embedded web catalog from one source.

Run with --check in CI to reject stale generated resources. Source-language
keys are deliberately shared by both UIs; placeholders use {0}, {1}, etc.
"""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def generated_files():
    messages = json.loads((ROOT / 'localization/messages.json').read_text())
    for key, value in messages.items():
        if sorted(re.findall(r'\{\d+\}', key)) != sorted(re.findall(r'\{\d+\}', value)):
            raise ValueError(f'Placeholder mismatch: {key}')
    # Fail before generating if a UI references a key with no translation.
    swift = (ROOT / 'platform/macos/FnCPNApp.swift').read_text()
    swift = '\n'.join(line for line in swift.splitlines() if not line.lstrip().startswith('//'))
    keys = re.findall(r'"([^"\n]*[\u4e00-\u9fff][^"\n]*)"', swift)
    html = (ROOT / 'internal/server/web/index.html').read_text()
    keys += re.findall(r'data-i18n(?:-[a-z-]+)?="([^"]+)"', html.split('<script>')[0])
    keys += re.findall(r"\bt\('([^'\n]+)'", html)
    missing = sorted(set(keys) - messages.keys())
    if missing:
        raise ValueError('Missing translations: ' + ', '.join(missing))
    files = {}
    for language in ['en', 'zh-Hans']:
        catalog = '// Generated by scripts/sync-localizations.py. Edit localization/messages.json.\n'
        for key, value in messages.items():
            catalog += f'{json.dumps(key, ensure_ascii=False)} = {json.dumps(value if language == "en" else key, ensure_ascii=False)};\n'
        files[ROOT / f'packaging/macos/{language}.lproj/Localizable.strings'] = catalog
    web = ROOT / 'internal/server/web/index.html'
    contents = web.read_text()
    contents, count = re.subn(r'    const english = \{.*?\n\};',
        lambda _: '    const english = ' + json.dumps(messages, ensure_ascii=False, indent=2) + ';',
        contents, count=1, flags=re.S)
    if count != 1:
        raise ValueError('Cannot find embedded web catalog')
    files[web] = contents
    return files


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    stale = []
    for path, contents in generated_files().items():
        if args.check:
            if not path.exists() or path.read_text() != contents:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(contents)
    if stale:
        parser.exit(1, 'Stale localization resources: ' + ', '.join(stale) + '\n')


if __name__ == '__main__':
    main()
